7853 2013-06-12 14:21:30.758 61720 INFO nova.compute.resource_tracker [-] Compute_service record updated for oz-controller:oz-controller
7854 2013-06-12 14:21:30.796 61720 INFO nova.compute.manager [-] Updating host status
7855 2013-06-12 14:21:52.299 61720 INFO nova.service [-] Caught SIGTERM, exiting
7856 2013-06-12 14:21:52.739 64851 INFO nova.manager [-] Skipping periodic task _periodic_update_dns because its interval is negative
7857 2013-06-12 14:21:52.808 64851 INFO nova.virt.driver [-] Loading compute driver 'nova.virt.libvirt.driver.LibvirtDriver'
7858 2013-06-12 14:21:52.947 INFO nova.openstack.common.rpc.common [req-3dbc2a89-9f18-4e03-b40f-ee4f627a8b03 None None] Connected to AMQP server on 10.10.10.53:5672
7859 2013-06-12 14:21:53.200 64851 AUDIT nova.service [-] Starting compute node (version 2013.1.1)
7860 2013-06-12 14:21:53.355 ERROR nova.virt.libvirt.driver [req-fe35dbc6-5252-4250-b040-35b2d2721b85 None None] NGKIM plug_vifs
7861 2013-06-12 14:21:53.355 ERROR nova.virt.libvirt.driver [req-fe35dbc6-5252-4250-b040-35b2d2721b85 None None] NGKIM plug_vifs vif_driver= <nova.virt.libvirt.mlnx.vif.MlxEthVIFDriver objec     t at 0x2631610> network= {'injected': False, 'bridge': None, 'multi_host': False, 'bridge_interface': None, 'cidr_v6': None, 'cidr': u'50.50.1.0/24', 'vlan': None, 'id': u'0bb8af79-c9b8     -4617-aa46-9c59e7e392ff'}
7862 2013-06-12 14:21:53.356 ERROR nova.virt.libvirt.mlnx.vif [req-fe35dbc6-5252-4250-b040-35b2d2721b85 None None] NGKIM vnic_mac= fa:16:3e:4b:6f:03 fabric= default
7863 2013-06-12 14:21:54.361 64851 CRITICAL nova [-] Processing Failure during vNIC plug
7864 2013-06-12 14:21:54.361 64851 TRACE nova Traceback (most recent call last):
7865 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/bin/nova-compute", line 85, in <module>
7866 2013-06-12 14:21:54.361 64851 TRACE nova     service.wait()
7867 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 689, in wait
7868 2013-06-12 14:21:54.361 64851 TRACE nova     _launcher.wait()
7869 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 209, in wait
7870 2013-06-12 14:21:54.361 64851 TRACE nova     super(ServiceLauncher, self).wait()
7871 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 179, in wait
7872 2013-06-12 14:21:54.361 64851 TRACE nova     service.wait()
7873 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 168, in wait
7874 2013-06-12 14:21:54.361 64851 TRACE nova     return self._exit_event.wait()
7875 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/eventlet/event.py", line 116, in wait
7876 2013-06-12 14:21:54.361 64851 TRACE nova     return hubs.get_hub().switch()
7877 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 187, in switch
7878 2013-06-12 14:21:54.361 64851 TRACE nova     return self.greenlet.switch()
7879 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 194, in main
7880 2013-06-12 14:21:54.361 64851 TRACE nova     result = function(*args, **kwargs)
7881 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 147, in run_server
7882 2013-06-12 14:21:54.361 64851 TRACE nova     server.start()
7883 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 429, in start
7884 2013-06-12 14:21:54.361 64851 TRACE nova     self.manager.init_host()
7885 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 599, in init_host
7886 2013-06-12 14:21:54.361 64851 TRACE nova     self._init_instance(context, instance)
7887 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 488, in _init_instance
7888 2013-06-12 14:21:54.361 64851 TRACE nova     self.driver.plug_vifs(instance, legacy_net_info)
7889 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 688, in plug_vifs
7890 2013-06-12 14:21:54.361 64851 TRACE nova     self.vif_driver.plug(instance, (network, mapping))
7891 2013-06-12 14:21:54.361 64851 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/mlnx/vif.py", line 98, in plug
7892 2013-06-12 14:21:54.361 64851 TRACE nova     raise exception.NovaException(_("Processing Failure during vNIC plug"))
7893 2013-06-12 14:21:54.361 64851 TRACE nova NovaException: Processing Failure during vNIC plug
7894 2013-06-12 14:21:54.361 64851 TRACE nova

